
default_target: all

#-------------------------------------------------------------------
# Project
#-------------------------------------------------------------------
PRJ_SQRL := service
PRJ_NAME := wlink
PRJ_DESC := wlink
PRJ_DEFS := 
PRJ_WINL := winmm strmiids
PRJ_VSLB := dshowbase

SQMOD_STATIC :=

PRJ_LIBROOT := ../../../../deftbuild/v1

#-------------------------------------------------------------------
# Configure build
#-------------------------------------------------------------------
include $(PRJ_LIBROOT)/config.mk

#-------------------------------------------------------------------
# Execute the build
#-------------------------------------------------------------------
include $(PRJ_LIBROOT)/go.mk

