
default_target: all

#-------------------------------------------------------------------
# Project
#-------------------------------------------------------------------
PRJ_QTWK := exe
#PRJ_DEPS := qt-win,qt-linux
PRJ_NAME := gtw
PRJ_DESC := Google Talk Widget
PRJ_DEFS := 
PRJ_WINL := winmm strmiids
PRJ_VSLB := dshowbase
PRJ_CIIX := *.htm
PRJ_GUIT := gui
#PRJ_RESD := res

SQMOD_STATIC :=

PRJ_LIBROOT := ../../../../deftbuild/v1

#-------------------------------------------------------------------
# Configure build
#-------------------------------------------------------------------
include $(PRJ_LIBROOT)/config.mk

#-------------------------------------------------------------------
# Execute the build
#-------------------------------------------------------------------
include $(PRJ_LIBROOT)/go.mk

