
# Total dependencies

makefiles   = $(wildcard *.mk)

.PHONY all: $(makefiles)
.PHONY rebuild: $(makefiles)
.PHONY clean: $(makefiles)

.PHONY $(makefiles) : 
	$(MAKE) -f $@ $(BUILDTYPE)
	

# DO NOT DELETE

v:\Code\pedge\lib2\winglib\dep/../../abel/lib/creatememory.obj: v:\Code\pedge\lib2\winglib\dep\..\..\abel\lib/libabplc5.h
