
default_target: all

#-------------------------------------------------------------------
# Project
#-------------------------------------------------------------------
PRJ_SQRL := exe
PRJ_NAME := topsize
PRJ_DESC := Shows largest files and folders
PRJ_DEFS := 
PRJ_WINL := winmm strmiids
PRJ_VSLB := dshowbase
PRJ_RESD := res

SQMOD_STATIC :=

PRJ_LIBROOT := ../../../../deftbuild/v1

#-------------------------------------------------------------------
# Configure build
#-------------------------------------------------------------------
include $(PRJ_LIBROOT)/config.mk

#-------------------------------------------------------------------
# Execute the build
#-------------------------------------------------------------------
include $(PRJ_LIBROOT)/go.mk

